### ISSUE TITLE
Unable to parse app drive

### ISSUE THREAD

**Issue by chammii1978** [missemily2022/GDriveUtils#1]
![Screenshot_2022-02-04-23-57-27-884_org telegram plus](https://user-images.githubusercontent.com/96408829/152583303-6b9bc707-7101-4367-9dd6-d06b6f2c2649.jpg)
Thanks in advance

**Comment by missemily2022** [comment]
Bro Did you put the AppDrive Email and Password?

Also send me the Bots Logs
